# Generated by Django 5.1.5 on 2025-02-09 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# 해당하는 카테고리 타입을 여기서 가져오고 create합니다.
def create_category_type(apps, schema_editor):
    if schema_editor.connection.alias == 'default':
        from expense.models import Category
        from expense.enums import CategoryType

        for category_type in CategoryType:
            Category.objects.using('default').create(
                id=category_type.code,
                name=category_type.name,
                description=category_type.description,
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('ETC', '기타'), ('tuition_fee', '학비'), ('book_fee', '교재비'), ('courses_fee', '인강비'), ('communication_fee', '통신요금'), ('food_fee', '식비'), ('transportation_fee', '대중교통비'), ('leisure_fee', '여가생활비'), ('self_development_fee', '자기개발비'), ('club_fee', '동아리 비용'), ('preparation_fee', '개인 물품비'), ('dormitory_fee', '기숙사비'), ('healthcare_fee', '건강 비용')], default='ETC', max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_money', models.PositiveIntegerField(default=0)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # 그리고 마이그레이션 파일로 category모델이 생성될때 파이썬으로 실행시킬 스크립트를 아래 정의해서 카테고리 타입에 정의되어있는
        # 모든 값들을 데이터베이스에 반영합니다.
        migrations.RunPython(create_category_type, migrations.RunPython.noop),
    ]
