# Generated by Django 5.1.5 on 2025-02-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_is_excluded'),
    ]

    operations = [
    ]
